auto update

diff --git a/.github/workflows/docker-push.yml b/.github/workflows/docker-push.yml
--- a/.github/workflows/docker-push.yml
+++ b/.github/workflows/docker-push.yml
@@ -1,23 +1,42 @@
 on:
   schedule:
-        - cron: "0 0 * * 0"
-  workflow_dispatch:
-    inputs:
-      tag:
-        description: "The tag version you want to build"
+    - cron: "0 0 * * 0"
   push:
-    paths:
-      - "v2ray.sh"
-      - "Dockerfile"
-      - ".github/workflows/docker-push.yml"
-  pull_request:
-    types: [opened, synchronize, reopened]
-    paths:
-      - "v2ray.sh"
-      - "Dockerfile"
-      - ".github/workflows/docker-push.yml"
 
 jobs:
+  check-version:
+    runs-on: ubuntu-latest
+    outputs:
+      version: ${{ steps.version.outputs.version }}
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          submodules: true
+          fetch-depth: 0
+
+      - name: Fetch version
+        id: version
+        run: |
+          # Check latest github release check-version:
+          repo="v2fly/v2ray-core"
+          version=$(curl -sSL --retry 5 "https://api.github.com/repos/${repo}/releases/latest" | jq -r .tag_name)
+          my_version="null"
+          if [ -f "version" ]; then
+            my_version=$(cat version | grep -E '^VERSION=' | cut -d '=' -f 2)
+          fi
+          commit_message="$(git log -1 --pretty=%B)"
+          if [ "$version" != "$my_version" ]; then
+            echo "Upstream version is $version, but my version is $my_version"
+          else
+            echo "Upstream version is $version"
+            if [[ $commit_message != *"[force]"* ]]; then
+              version="null"
+            fi
+          fi
+          echo "version=$version" >> $GITHUB_OUTPUT
+          echo $version
+
   check-env:
     permissions:
       contents: none
@@ -34,12 +53,14 @@ jobs:
 
   build:
     runs-on: ubuntu-latest
-    needs: check-env
-    if: needs.check-env.outputs.check-docker == 'true'
+    needs:
+      - check-env
+      - check-version
+    if: needs.check-env.outputs.check-docker == 'true' && needs.check-version.outputs.version != 'null'
     timeout-minutes: 120
     permissions:
       packages: write
-      contents: read
+      contents: write
       id-token: write
     steps:
       - name: Checkout codebase
@@ -49,18 +70,31 @@ jobs:
         id: tag
         run: |
           repo=v2fly/v2ray-core
-          tag=$(curl -sSL --retry 5 "https://api.github.com/repos/${repo}/releases/latest" | jq .tag_name | awk -F '"' '{print $2}')
-          if [[ -z "${{ github.event.inputs.tag }}" ]]; then
-            echo "Use the latest release tag of v2ray-core: ${tag}"
-          else
-            echo "Use tag: ${{ github.event.inputs.tag }}"
-            tag="${{ github.event.inputs.tag }}"
-          fi
+          tag=${{ needs.check-version.outputs.version }}
+          # tag=$(curl -sSL --retry 5 "https://api.github.com/repos/${repo}/releases/latest" | jq .tag_name | awk -F '"' '{print $2}')
           read type tag_sha < <(echo $(curl -sSL --retry 5 "https://api.github.com/repos/$repo/git/ref/tags/$tag" |  jq -r '.object.type,.object.sha'))
           echo "tag=${tag}" >> $GITHUB_OUTPUT
           echo "sha=${tag_sha}" >> $GITHUB_OUTPUT
           echo "short_sha=$(echo $tag_sha | cut -c1-7)" >> $GITHUB_OUTPUT
           echo "pkg=v2fly-core" >> $GITHUB_OUTPUT
+
+      - name: Update version file
+        run: |
+          echo "VERSION=${{ steps.tag.outputs.tag }}" > version
+          echo "SHA=${{ steps.tag.outputs.sha }}" >> version
+          echo "SHORT_SHA=${{ steps.tag.outputs.short_sha }}" >> version
+          git config --local user.name "github-actions[bot]"
+          git config --local user.email "${{ github.actor_id }}+github-actions[bot]@users.noreply.github.com"
+          git add version
+          git commit -m "Update version to ${{ steps.tag.outputs.tag }} [skip ci]" || echo "No changes to commit"
+
+      - name: Push changes
+        uses: ad-m/github-push-action@v0.8.0
+        with:
+          branch: ${{ github.head_ref }}
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          tags: true
+          force: true
 
       - name: Setup QEMU
         uses: docker/setup-qemu-action@v3
@@ -108,3 +142,4 @@ jobs:
           cache-to: type=gha,mode=max,scope=docker-release
           build-args: |
             TAG=${{ steps.tag.outputs.tag }}
+            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
